server:
  port: 8090

spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  data:
    mongodb:
      host: localhost
      database: treegrowth-web
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/treegrowth
      username: wusi
      password: 666666
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
